name: "Publish to Docker"
description: "Build a container image"

inputs:
  image_name:
    description: "Name of the image to build"
  tag: 
    description: "How to tag the image. Default: latest"    

runs:
  using: "composite"
  steps:
      - name: Setup BuildX
        uses: docker/setup-buildx-action@v1
      
      - name: Set the tag
        shell: bash
        run: |
          if [ -z "${{inputs.tag}}" ]
          then
            echo "final_tag=latest" >> $GITHUB_ENV
          else
            echo "final_tag=${{inputs.tag}}" >> $GITHUB_ENV
          fi
      
      - name: Build the Image (Not pushing)
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: ${{inputs.image_name}}:${{env.final_tag}}
